version: "3.9"
services:
  web:
    build:
      context: .
      target: runner
    container_name: app-next-prod
    ports:
      - "3000:3000"
    env_file:
      - ./.env.production
    restart: unless-stopped
