version: "3.9"
services:
  web:
    build:
      context: .
      target: dev
    container_name: app-next-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
